apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: swe645-angular
  name: swe645-angular
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: swe645-angular
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: swe645-angular
    spec:
      containers:
        - image: gcr.io/core-hash-274103/github.com/haramrit09k/swe645-angular
          imagePullPolicy: IfNotPresent
          name: swe645-angular-1
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: swe645-angular
  name: swe645-angular-hpa-oraz
  namespace: default
spec:
  maxReplicas: 5
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 80
      type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: swe645-angular
